<?php


/**
 * Implements hook_form_FORM_ID_alter() for carlos_form_form().
 */
function andres_form_carlos_form_form_alter(&$form, &$form_state) {
	$bool_edit_user = FALSE;   // variable booleana
  if (!empty($form_state['storage']['user'])) {   //condicion para que lo que reciba d user si id esta vacio haga
    $tel = $form_state['storage']['user']->getUserTel();
    $bool_edit_user = TRUE;
  }
  $form['name']['#weight'] = 1;
  $form['lastname']['#weight'] = 2;
  $form['age']['#weight'] = 4;
  $form['opsex']['#weight'] = 5;
  $form['create']['#weight'] = 6;
  $form['update']['#weight'] = 7;
  $form['new_account']['#weight'] = 8;
  $form['tel'] = array(
    '#type' => 'textfield',
    '#title' => t('Type your phone number'),
    '#default_value' => $bool_edit_user ? $tel : '',
    '#weight' => 3,
  );
  $form['#validate'][] = 'andres_new_validate';
  $form['#submit'][] = 'andres_new_submit';
}


/**
 * { function_description }
 *
 * @param      <type>  $form        The form
 * @param      <type>  $form_state  The form state
 */
function andres_new_validate ($form, &$form_state) {
    if (empty($form_state['values']['tel'])) {   
    form_set_error('tel', t('Error, este campo es requerido.')); 
  }
}

/**
 * { function_description }
 *
 * @param      <type>  $form        The form
 * @param      <type>  $form_state  The form state
 */
function andres_new_submit ($form, &$form_state) {
  /*db_update('usuarios')
  	->fields([
  		'tel' => $form_state['values']['tel']
  	])
  	->condition('id', $form_state['storage']['last_id'])
  	->execute();*/
}


