<?php

/**
 * Implements hook_permission().
 */
function sicnotas_register_permission() {
  return array(
    'sicnotas staff permission' =>  array(
      'title' => t('permission to access'),
      'description' => t('Define who can access to this module'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sicnotas_register_menu() {

  $items['staff-register'] = array(
    'title' => t('Staff registration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sicnotas_register_staff_form'),
    'access arguments' => array('sicnotas staff permission'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'inc/sicnotas_register_staff.inc'
  );

  $items['students-register'] = array(
    'title' => t('Students registration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sicnotas_register_students_form'),
    'access arguments' => array('sicnotas staff permission'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'inc/sicnotas_register_students.inc'
  );
  return $items;
}

/**
 * Implements hook_form_id_alter().
 * se desactivan los checkbox de los roles que no son profesores o administradores
 */
function sicnotas_register_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    $roles = $form['account']['roles']['#options'];
    dpm($roles,'roles');
    $allowedRoles = ['Teacher', 'School administrator'];
    foreach ($roles as $key => $value) {
      if ($value == 'Teacher' || $value == 'School administrator') {
        $rol_filter = array_filter($roles, function ($nameRol) use($allowedRoles) {
        return in_array($nameRol, $allowedRoles);
        });
        $form['account']['roles']['#options'] = $rol_filter;
        // se desactiva el checkbox de usuario autenticado
        unset($form['account']['roles'][2]);
      }
    }
  }
}
